### ISSUE TITLE
可以说下具体怎么用吗

### ISSUE THREAD

**Issue by peter2022Begin** [ChinaFishNews/AutoSignature#1]

**Comment by ChinaFishNews** [comment]
https://chinafishnews.github.io/2018/06/20/ipa包重签名探究/
上面是博客地址，你可以看下

**Comment by peter2022Begin** [comment]
我看了你的文章然后直接复制那个脚本到run script,运行后出现
The file “xxx.app” couldn’t be opened because you don’t have permission to view it.

直接运行你的demo也是出现这个提示

**Comment by ChinaFishNews** [comment]
那个脚本要给他可执行权限(chmod +x autoResign.sh)

**Comment by ChinaFishNews** [comment]
不然没有执行权限

**Comment by peter2022Begin** [comment]
现在报这个错误
/Users/xxx/Library/Developer/Xcode/DerivedData/XXX-dvuausnfhghodqgfinzcabmlipxw/Build/Products/Debug-iphoneos/XXX.app/Frameworks/*: No such file or directory

不管debug还是release都报错了

**Comment by ChinaFishNews** [comment]
这就是没找到对应的framework 
脚本里的这个INJECT_FRAMEWORK_RELATIVE_PATH变量要改成你自己的路径
